export const BLOK_LIST_REQUEST = 'BLOK_LIST_REQUEST'
export const BLOK_LIST_SUCCESS = 'BLOK_LIST_SUCCESS'
export const BLOK_LIST_FAIL = 'BLOK_LIST_FAIL'

export const BLOK_CREATE_REQUEST = 'BLOK_CREATE_REQUEST'
export const BLOK_CREATE_SUCCESS = 'BLOK_CREATE_SUCCESS'
export const BLOK_CREATE_FAIL = 'BLOK_CREATE_FAIL'

export const BLOK_DELETE_REQUEST = 'BLOK_DELETE_REQUEST'
export const BLOK_DELETE_SUCCESS = 'BLOK_DELETE_SUCCESS'
export const BLOK_DELETE_FAIL = 'BLOK_DELETE_FAIL'

export const BLOK_UPDATE_REQUEST = 'BLOK_UPDATE_REQUEST'
export const BLOK_UPDATE_SUCCESS = 'BLOK_UPDATE_SUCCESS'
export const BLOK_UPDATE_FAIL = 'BLOK_UPDATE_FAIL'
