export const BOOKMARK_LIST_REQUEST = 'BOOKMARK_LIST_REQUEST';
export const BOOKMARK_LIST_SUCCESS = 'BOOKMARK_LIST_SUCCESS';
export const BOOKMARK_LIST_FAIL = 'BOOKMARK_LIST_FAIL';

export const BOOKMARK_CREATE_REQUEST = 'BOOKMARK_CREATE_REQUEST';
export const BOOKMARK_CREATE_SUCCESS = 'BOOKMARK_CREATE_SUCCESS';
export const BOOKMARK_CREATE_FAIL = 'BOOKMARK_CREATE_FAIL';

export const BOOKMARK_DELETE_REQUEST = 'BOOKMARK_DELETE_REQUEST';
export const BOOKMARK_DELETE_SUCCESS = 'BOOKMARK_DELETE_SUCCESS';
export const BOOKMARK_DELETE_FAIL = 'BOOKMARK_DELETE_FAIL';

export const BOOKMARK_UPDATE_REQUEST = 'BOOKMARK_UPDATE_REQUEST';
export const BOOKMARK_UPDATE_SUCCESS = 'BOOKMARK_UPDATE_SUCCESS';
export const BOOKMARK_UPDATE_FAIL = 'BOOKMARK_UPDATE_FAIL';
